Gemfile
Gemfile.lock
spec/features/login_spec.rb
spec/rails_helper.rb

Twitter ログインに関する feature テストを追加

---

app/assets/javascripts/application.js
app/assets/javascripts/slider.js
app/assets/stylesheets/application.css
app/views/mikanzs/edit.html.erb
app/views/mikanzs/new.html.erb
config/environments/production.rb
vendor/assets/javascripts/bootstrap-slider.js
vendor/assets/stylesheets/bootstrap-slider.css

http://qa.atmarkit.co.jp/q/3017
https://groups.google.com/forum/#!topic/twitter-bootstrap-stackoverflow/sgELG6Cc2c0
https://github.com/seiyria/bootstrap-slider
http://www.eyecon.ro/bootstrap-slider/
ここらへんを参考に。

gem を使わずに bootstrap-slider を使ってみる

---

Gemfile
Gemfile.lock
app/controllers/mikanzs_controller.rb
app/models/mikanz.rb
app/uploaders/mikanz_image_uploader.rb
app/views/mikanzs/edit.html.erb
app/views/mikanzs/new.html.erb
app/views/mikanzs/show.html.erb
config/initializers/carrierwave.rb
config/locales/ar_ja.yml
config/locales/carrierwave_ja.yml
db/migrate/20150214104515_add_mikanz_image_to_mikanz.rb
db/schema.rb
spec/factories/mikanzs.rb
spec/models/mikanz_spec.rb
spec/uploaders/mikanz_image_uploader_spec.rb

* アップロード先は `Amazon S3`
* 開発時と本番時でアップロード先を分ける

[WIP] 各ミカンに画像のアップロードを行えるようにする

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5977251087725089709">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150228014205

---

Gemfile
Gemfile.lock
spec/features/create_watering_spec.rb
spec/rails_helper.rb

水やり機能周りのエンドツーエンドのテストを追加する。
今後も同様のケースにおいてテストを追加するかどうかは別として。

JS が絡むエンドツーエンドテストの追加

---

app/controllers/waterings_controller.rb
app/helpers/application_helper.rb
app/views/mikanzs/show.html.erb
spec/controllers/waterings_controller_spec.rb

自分のミカンには応援できないようにする

---

Gemfile
Gemfile.lock
app/models/mikanz.rb
app/models/user.rb
app/models/watering.rb
spec/factories/mikanzs.rb
spec/factories/users.rb
spec/factories/waterings.rb
spec/models/mikanz_spec.rb
spec/models/user_spec.rb
spec/models/watering_spec.rb

各モデルのプロパティコメントを追加したい

---

app/helpers/application_helper.rb
app/views/mikanzs/show.html.erb
vendor/assets/stylesheets/custom.css

ミカン情報の表示方法を改善

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5987398107314920152">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150328014211

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5989934861434746129">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150404014209

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5992470651636222149">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150411013910

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5995007364998056932">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150418013910

---

app/controllers/top_controller.rb
spec/controllers/top_controller_spec.rb

「最近登録されたミカン」が登録日で降順になってないのを修正

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/tag.coffee
app/assets/stylesheets/application.css
app/controllers/mikanzs_controller.rb
app/models/mikanz.rb
app/views/mikanzs/_tags.html.erb
app/views/mikanzs/edit.html.erb
app/views/mikanzs/new.html.erb
app/views/mikanzs/show.html.erb
app/views/top/index.html.erb
config/locales/ar_ja.yml
db/migrate/20150505010122_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
db/migrate/20150505010123_add_missing_unique_indices.acts_as_taggable_on_engine.rb
db/migrate/20150505010124_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
db/migrate/20150505010125_add_missing_taggable_index.acts_as_taggable_on_engine.rb
db/migrate/20150505010126_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
db/schema.rb
spec/controllers/mikanzs_controller_spec.rb
spec/factories/mikanzs.rb
vendor/assets/javascripts/tag-it.js
vendor/assets/stylesheets/jquery.tagit.css
vendor/assets/stylesheets/tagit.ui-zendesk.css

#23
http://qiita.com/tyamagu2/items/75eeaa8ef208385aa341 これを見ながらやってみる
* `rake acts_as_taggable_on_engine:install:migrations`
* `rake db:migrate`

ミカンのタグ分類を可能にする

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6002617510486444490">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150509013915

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/tag_autocomplete.coffee
app/controllers/mikanzs_controller.rb
app/views/layouts/application.html.erb
vendor/assets/stylesheets/custom.css

issue #62
http://qiita.com/tyamagu2/items/75eeaa8ef208385aa341#%E3%82%AA%E3%83%BC%E3%83%88%E3%82%B3%E3%83%B3%E3%83%97%E3%83%AA%E3%83%BC%E3%83%88 を参考に

タグの入力をオートコンプリート可能にする

---

app/controllers/top_controller.rb
app/helpers/top_helper.rb
app/views/top/index.html.erb
config/routes.rb
spec/controllers/top_controller_spec.rb
vendor/assets/stylesheets/custom.css

トップページにタグクラウドを表示する

---

config/routes.rb

`bundle exec annotate --routes` する

---

.gitignore
Gemfile
Gemfile.lock

Use `rails_best_practices` gem

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6005154229926811416">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150516013914

---

app/controllers/mikanzs_controller.rb
app/models/mikanz.rb
app/views/mikanzs/edit.html.erb
app/views/mikanzs/new.html.erb
app/views/mikanzs/show.html.erb
app/views/top/index.html.erb
db/migrate/20150520121300_remove_start_time_from_mikanz.rb
db/schema.rb
spec/controllers/mikanzs_controller_spec.rb
spec/factories/mikanzs.rb
spec/models/mikanz_spec.rb

既存の「作成開始日」項目を消す

---

app/controllers/mikanzs_controller.rb
app/models/mikanz.rb
app/views/mikanzs/_input_start.html.erb
app/views/mikanzs/edit.html.erb
app/views/mikanzs/new.html.erb
app/views/mikanzs/show.html.erb
app/views/top/index.html.erb
config/locales/ar_ja.yml
db/migrate/20150520131158_add_start_year_and_start_month_to_mikanz.rb
db/schema.rb
spec/controllers/mikanzs_controller_spec.rb
spec/factories/mikanzs.rb
spec/models/mikanz_spec.rb

「ミカンの生まれ年」「ミカンの生まれ月」の２項目を新たに追加

---

README.md

README に準備関連の事を追加

---

app/controllers/mikanzs_controller.rb
app/views/mikanzs/show.html.erb
app/views/mikanzs/tag_search.html
app/views/top/index.html.erb
spec/controllers/mikanzs_controller_spec.rb

タグをクリックしたらそのミカンの一覧を表示できるようにする

---

app/views/top/index.html.erb

これがどんなサービスかを端的に説明する文章をトップページに追加

---

Gemfile
Gemfile.lock
app/controllers/mikanzs_controller.rb
app/views/mikanzs/tag_search.html
app/views/mikanzs/users_mikanzs.html.erb
config/initializers/kaminari_config.rb
spec/controllers/mikanzs_controller_spec.rb
vendor/assets/stylesheets/custom.css

ページネーションの追加

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6012764370232018399">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150606013911

---

app/controllers/waterings_controller.rb
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/waterings/users_waterings.html.erb
config/routes.rb
spec/controllers/waterings_controller_spec.rb

issue #101 
ログインユーザー専用のメニューとして、
* 自分のミカン一覧
* 自分が応援したミカン一覧
を追加する

ログインユーザー専用のメニューを用意する

---

app/models/notification.rb
app/models/user.rb
app/views/users/notifications.html.erb
spec/models/user_spec.rb

新規ユーザー登録時、ようこそ的なおしらせを登録する

---

app/controllers/sessions_controller.rb
config/initializers/omniauth.rb
config/routes.rb

Twitter ログインキャンセル時の考慮漏れ

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/mikanzs_controller.rb
app/controllers/users_controller.rb
app/controllers/waterings_controller.rb
app/helpers/application_helper.rb
app/models/Notifier.rb
app/models/notifier.rb
app/models/user.rb
app/views/mikanzs/show.html.erb
app/views/top/index.html.erb

エラーなどの slack 通知

---

config/database.yml
config/environments/staging.rb
config/initializers/carrierwave.rb
config/secrets.yml

mikans-stg をステージングとして利用できるようにする

---

circle.yml
scripts/feature_deploy.sh

mikans-stg を捨てる

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
config/environments/production.rb

Google analytics をいれる

---

Gemfile
Gemfile.lock
Procfile
config/unicorn_production.rb

staging / production （いずれも heroku）で Unicorn を使う

---

Gemfile
Gemfile.lock
config/newrelic.yml

New relic をつかう

---

app/views/top/index.html.erb
vendor/assets/stylesheets/custom.css

ソーシャルボタンを追加

---

Gemfile
config/database.yml
config/environments/iaas.rb
config/secrets.yml
config/unicorn.rb

Relate with https://github.com/a-know/rails-server-cookbook

Enable gce vm environment

---

config/deploy.rb
config/unicorn.rb

GCE インスタンス上でうまくアプリを表示できない問題への対処

Fix deploy config
